In [3]:
import numpy as np

#### 2.1. 배열의 index 접근하기

In [29]:
print('1차원 배열')
arr1 = np.array([0,1,2,3,4,5,6,7,8,9])
arr2 = np.arange(10)
print(arr1 == arr2)
print(arr2)
print("끝에서 2번째 값: ",arr1[-2]) # 끝에서 2번째 값
print("arr1[3:8] => ",arr1[3:8])
print("arr1[3: ] => ",arr1[3:])
print("arr1[ :7] => ",arr1[:7])
print("arr1[:-1] => ",arr1[:-1])

print("\n2차원 배열")
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr, arr.shape, arr.ndim, arr[-1][-1])
print(arr[0])
print(arr[:, 1])
print(arr[:2, 2:])

1차원 배열
[ True  True  True  True  True  True  True  True  True  True]
[0 1 2 3 4 5 6 7 8 9]
끝에서 2번째 값:  8
arr1[3:8] =>  [3 4 5 6 7]
arr1[3: ] =>  [3 4 5 6 7 8 9]
arr1[ :7] =>  [0 1 2 3 4 5 6]
arr1[:-1] =>  [0 1 2 3 4 5 6 7 8]

2차원 배열
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 2 9
[1 2 3]
[2 5 8]
[[3]
 [6]]


#### 2.2. Fancy 인덱싱(특정 원소를 지정)

In [34]:
print('1차원 배열')
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[[0, 2, 4]])

print("\n2차원 배열")
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[[0, 2], 2:])
print(arr[1:, [1,2]])

1차원 배열
[ 5 15 25]

2차원 배열
[[3]
 [9]]
[[5 6]
 [8 9]]


#### 2.3. Boolean 인덱싱

In [44]:
print('1차원 배열')
arr = np.array([0,1,2,3,4])
print(arr[[True, False, True, False, True]])

print("\n2차원 배열")
arr = np.array([[1,2,3], [4,5,6]])
print(arr[[True, False], True])

print("\n범위지정: ",arr[arr > 3])

1차원 배열
[0 2 4]

2차원 배열
[[1 2 3]]

범위지정:  [4 5 6]
