In [1]:
import numpy as np

#### 4.1. 1차원 배열의 정렬

In [7]:
arr = np.random.randint(10, size=10)
print("1. 원본    : ",arr)
print("2. 올림차순: ", np.sort(arr))         # 올림차순 정렬
print("3. 내림차순: ", np.sort(arr)[::-1])   # 내림차순 정렬

1. 원본    :  [8 2 0 2 0 1 7 0 0 5]
2. 올림차순:  [0 0 0 0 1 2 2 5 7 8]
3. 내림차순:  [8 7 5 2 2 1 0 0 0 0]


#### 4.2. 2차원 배열의 정렬

In [22]:
arr = np.random.randint(15, size=(3,4))
print("1. 원본: \n",arr)
print("\n2. 1차원으로 정렬: ", np.sort(arr, axis=None))
print("\n3. 열 기준 정렬: \n", np.sort(arr, axis=0))
print("\n4. 행 기준 정렬: \n", np.sort(arr, axis=1))

# argsort : 정렬한 index 반환
print("\n5. 1차원으로 정렬: ",np.argsort(arr, axis=None))
print("\n6. 열 기준 정렬: \n", np.argsort(arr, axis=0))
print("\n7. 행 기준 정렬: \n", np.argsort(arr, axis=1))

1. 원본: 
 [[ 3  4  7  5]
 [13  7 13  7]
 [ 8 13  0  4]]

2. 1차원으로 정렬:  [ 0  3  4  4  5  7  7  7  8 13 13 13]

3. 열 기준 정렬: 
 [[ 3  4  0  4]
 [ 8  7  7  5]
 [13 13 13  7]]

4. 행 기준 정렬: 
 [[ 3  4  5  7]
 [ 7  7 13 13]
 [ 0  4  8 13]]

5. 1차원으로 정렬:  [10  0  1 11  3  2  5  7  8  4  6  9]

6. 열 기준 정렬: 
 [[0 0 2 2]
 [2 1 0 0]
 [1 2 1 1]]

7. 행 기준 정렬: 
 [[0 1 3 2]
 [1 3 0 2]
 [2 3 0 1]]
