In [1]:
import numpy as np

#### 5.1. 배열의 형태 변경1: reshape()

In [11]:
arr = np.arange(12)
print(arr.ndim, "차원 배열: ",arr)

arr = arr.reshape(3,4)
print(arr.ndim, "차원 배열: \n",arr)

arr = arr.reshape(2, 2, 1, 3)
print(arr.ndim, "차원 배열: \n",arr)

1 차원 배열:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
2 차원 배열: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4 차원 배열: 
 [[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]]


#### 5.2. 배열의 형태 변경2: resize(), ravel()

In [18]:
arr = np.arange(1, 13)
print("1. 원본: ",arr)

arr.resize(3, 4)
print("\n2. 차원 변경: \n",arr)

arr = arr.ravel()
print("\n3. 1차원으로 변경: ",arr)

1. 원본:  [ 1  2  3  4  5  6  7  8  9 10 11 12]

2. 차원 변경: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

3. 1차원으로 변경:  [ 1  2  3  4  5  6  7  8  9 10 11 12]


#### 5.3. 배열의 형태 변경3: expand_dims(), squeeze()

In [43]:
print("# expand_dims() : 차원 확장")
arr = np.array([1,2,3])
print("1. 원본: ",arr, arr.shape)

arr = np.expand_dims(arr, axis=0)
print("\n2. 열 차원 추가: ",arr, arr.shape)

arr = np.array([1,2,3])
arr = np.expand_dims(arr, axis=1)
print("\n3. 행 차원 추가:  \n",arr, arr.shape)

print("\n# squeeze() : 차원 축소")
arr = np.array([[1,2]])
print("4. ", arr.ndim,"차원: ",arr, arr.shape)

arr = np.squeeze(arr, axis=0)
print("\n5. ", arr.ndim, "차원: ", arr, arr.shape)

arr = np.array([[[1,2,3]]])
print("\n6. ", arr.ndim,"차원: ",arr, arr.shape)

arr = np.squeeze(arr)
print("\n7. ", arr.ndim,"차원: ",arr, arr.shape)

# expand_dims() : 차원 확장
1. 원본:  [1 2 3] (3,)

2. 열 차원 추가:  [[1 2 3]] (1, 3)

3. 행 차원 추가:  
 [[1]
 [2]
 [3]] (3, 1)

# squeeze() : 차원 축소
4.  2 차원:  [[1 2]] (1, 2)

5.  1 차원:  [1 2] (2,)

6.  3 차원:  [[[1 2 3]]] (1, 1, 3)

7.  1 차원:  [1 2 3] (3,)


#### 5.4. 전치행렬(Transpose Matrix)

In [61]:
print("""[전치 행렬 예제] 행과 열을 교환한다.
A B        A C
C D   =>   B D
""")
arr = np.array([['A', 'B'],
                ['C', 'D']])
print("1. 예제: \n", arr.T)

arr = np.array([['A', 'B'],
                ['C', 'D'],
                ['E', 'F']])
print("\n2. 예제: \n",arr.T,"\n\n")

# 행렬 곱
arr1 = np.array([[1, 2],
                [3, 4],
                [5, 6]]);
arr2 = np.full((3,2), 2)
# print(arr1.dot(arr2)) # 오류: 행과 열이 일치해야 한다.
print(arr1)
print(arr2)
print("\n3. 행렬 곱: \n",(arr1).dot(arr2.T))

[전치 행렬 예제] 행과 열을 교환한다.
A B        A C
C D   =>   B D

1. 예제: 
 [['A' 'C']
 ['B' 'D']]

2. 예제: 
 [['A' 'C' 'E']
 ['B' 'D' 'F']] 


[[1 2]
 [3 4]
 [5 6]]
[[2 2]
 [2 2]
 [2 2]]

3. 행렬 곱: 
 [[ 6  6  6]
 [14 14 14]
 [22 22 22]]
