In [3]:
import numpy as np

#### 6.1. 배열에 원소 추가 및 삭제

In [20]:
print("[1차원] 추가 insert")
arr = [1,2,3,4]
arr.insert(2, 20)
print("1.1. List 예제: ",arr)

arr = np.arange(1, 5)
arr = np.insert(arr, 2, 50)
print("\n1.2. numpy array 예제: ",arr)

print("\n[2차원] 추가 insert")
arr = np.arange(1, 5).reshape(2,2)
print("2.1. ", np.insert(arr, 2, 20, axis=None))
print("2.2. \n", np.insert(arr, 2, 20, axis=0))
print("2.3. \n", np.insert(arr, 2, 20, axis=1))

print("\n[2차원] 삭제 delete")
arr = np.arange(1, 5).reshape(2,2)
print("3.1. 원본\n",arr)
print("\n3.2. \n", np.delete(arr, 1, axis=None))
print("\n3.3. \n", np.delete(arr, 1, axis=0))
print("\n3.4. \n", np.delete(arr, 1, axis=1))

[1차원] 추가 insert
1.1. List 예제:  [1, 2, 20, 3, 4]

1.2. numpy array 예제:  [ 1  2 50  3  4]

[2차원] 추가 insert
2.1.  [ 1  2 20  3  4]
2.2. 
 [[ 1  2]
 [ 3  4]
 [20 20]]
2.3. 
 [[ 1  2 20]
 [ 3  4 20]]

[2차원] 삭제 delete
3.1. 원본
 [[1 2]
 [3 4]]

3.2. 
 [1 3 4]

3.3. 
 [[1 2]]

3.4. 
 [[1]
 [3]]


#### 6.2. 배열 간의 병합(append, vstack, hstack, concatenate)

In [54]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(1,5).reshape(2,2)
# append
print("1.1. append:", np.append(arr1, arr2, axis=None))
print("\n1.2. append(vstack):\n", np.append(arr1, arr2, axis=0)) # vstack
print("\n1.3. append(hstack):\n", np.append(arr1, arr2, axis=1)) # hstack
# vstack, hstack
print("\n2.1. vstack(axis=0):\n", np.vstack((arr1, arr2)))
print("\n2.2. hstack(axis=1):\n", np.hstack((arr1, arr2)))
# concatenate
print("\n3.1. concatenate:\n", np.concatenate([arr1, arr2], axis=None))
print("\n3.2. concatenate:\n", np.concatenate([arr1, arr2], axis=0))
print("\n3.3. concatenate:\n", np.concatenate([arr1, arr2], axis=1))

1.1. append: [1 2 3 4 1 2 3 4]

1.2. append(vstack):
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]

1.3. append(hstack):
 [[1 2 1 2]
 [3 4 3 4]]

2.1. vstack(axis=0):
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]

2.2. hstack(axis=1):
 [[1 2 1 2]
 [3 4 3 4]]

3.1. concatenate:
 [1 2 3 4 1 2 3 4]

3.2. concatenate:
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]

3.3. concatenate:
 [[1 2 1 2]
 [3 4 3 4]]


#### 6.3. 배열 분할: vsplit, hsplit

In [75]:
# 2차원
arr = np.arange(1,5).reshape(2,2)
print("1.1. 원본: \n",arr)

print("\n1.2. vsplit: \n",np.vsplit(arr, 2)) # vsplit() => axis=0
print("\n1.3. hsplit: \n",np.hsplit(arr, 1)) # hsplit() => axis=1

# 3차원
arr = np.random.randint(0,10, (2,4,6))
print("\n2.1. 원본: \n",arr)
print("\n2.2. vsplit: \n",np.vsplit(arr, 2))
print("\n2.3. hsplit: \n",np.hsplit(arr, 2))

1.1. 원본: 
 [[1 2]
 [3 4]]

1.2. vsplit: 
 [array([[1, 2]]), array([[3, 4]])]

1.3. hsplit: 
 [array([[1, 2],
       [3, 4]])]

2.1. 원본: 
 [[[5 8 9 5 7 2]
  [2 4 1 5 5 3]
  [3 5 0 8 1 2]
  [3 9 5 8 3 4]]

 [[7 2 0 4 5 9]
  [7 1 0 1 8 3]
  [7 0 5 9 4 5]
  [8 0 8 4 3 5]]]

2.2. vsplit: 
 [array([[[5, 8, 9, 5, 7, 2],
        [2, 4, 1, 5, 5, 3],
        [3, 5, 0, 8, 1, 2],
        [3, 9, 5, 8, 3, 4]]]), array([[[7, 2, 0, 4, 5, 9],
        [7, 1, 0, 1, 8, 3],
        [7, 0, 5, 9, 4, 5],
        [8, 0, 8, 4, 3, 5]]])]

2.3. hsplit: 
 [array([[[5, 8, 9, 5, 7, 2],
        [2, 4, 1, 5, 5, 3]],

       [[7, 2, 0, 4, 5, 9],
        [7, 1, 0, 1, 8, 3]]]), array([[[3, 5, 0, 8, 1, 2],
        [3, 9, 5, 8, 3, 4]],

       [[7, 0, 5, 9, 4, 5],
        [8, 0, 8, 4, 3, 5]]])]
