In [2]:
import numpy as np

#### <실습예제 1>
- 원소가 모두 3인(3,4,5) 형태의 numpy.array를 출력하시오.

In [6]:
arr = np.full([3,4,5], 3)
print(arr)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


#### <실습예제 2>
- 정수 -50 ~ 50의 범위 안의 난수로 이루어진 (4,5) 형태의 numpy.array를 출력
- 행을 기준으로 오름차순 정렬한 결과와
- 전체 배열을 1차원 배열로 변경하여 오름차순 정렬한 결과를 출력하시오.

In [20]:
arr = np.random.randint(-50, 50, (4,5))
print("1. 원본: \n", arr)
print("\n2. 2차원 배열형태: \n",np.sort(arr, axis=0))
print("\n3. 1차원 배열형태: \n",np.sort(arr, axis=None))

1. 원본: 
 [[ -2   2 -43   8 -43]
 [ 17 -35   6  -2 -48]
 [ 39  15 -38  30 -17]
 [  5 -38  47 -22  -3]]

2. 2차원 배열형태: 
 [[ -2 -38 -43 -22 -48]
 [  5 -35 -38  -2 -43]
 [ 17   2   6   8 -17]
 [ 39  15  47  30  -3]]
[[ -2 -38 -43 -22 -48]
 [  5 -35 -38  -2 -43]
 [ 17   2   6   8 -17]
 [ 39  15  47  30  -3]]

3. 1차원 배열형태: 
 [-48 -43 -43 -38 -38 -35 -22 -17  -3  -2  -2   2   5   6   8  15  17  30
  39  47]


#### <실습예제 3>
- 다음과 같은 파이썬 list 가 존재한다.
- list 안에 있는 각 numpy.array의 원소들의 평균값과 표준편찬, 중앙값을 순서대로 구하시오.
- 구한 순서대로 원소가 이루어진 새로운 list를 구성하고 출력하시오.

In [30]:
lst = [
    np.full(3,8),
    np.array([33, -15, 26]),
    np.linspace(17, 26, 3)
]
print("1. 원본: \n",lst)

lst2 = []
for el in lst:
    lst2.append(np.mean(el))   # 평균값
    lst2.append(np.std(el))    # 표준편차
    lst2.append(np.median(el)) # 중앙값
print("\n2. 결과: \n", lst2)

1. 원본: 
 [array([8, 8, 8]), array([ 33, -15,  26]), array([17. , 21.5, 26. ])]

2. 결과: 
 [8.0, 0.0, 8.0, 14.666666666666666, 21.171259344267224, 26.0, 21.5, 3.6742346141747673, 21.5]


#### <실습예제 4>
- arr = np.arange(2, 20, 2).reshape((3,3))
- 다음과 같은 numpy.array 가 존재한다. 
- 이 배열을 행을 기준으로 3개의 배열로 분활한다.
- 분할된 각 배열의 원소들을 제곱한 결과를 다시 원본 배열에 행을 기준으로 병합하시오.
- 단, 마지막 출력 결과는 원본 배열과 차원이 같아야 한다

In [50]:
arr = np.arange(2, 20, 2).reshape((3,3))
print("1. 원본: \n", arr)

arr1 = np.vsplit(arr, 3)        # 3개로 분활
print("\n2. 3개로 분활: \n",arr1)

arr2 = np.square(arr1)          # 각 원소를 제곱한다.
print("\n3. 각 원소를 제곱: \n",arr2)

arr3 = np.squeeze(arr2, axis=1) # 차원 축소
arr3 = np.vstack((arr, arr3))   # 원본과 제곱결과를 병합
print("\n4. 행 기준으로 병합: \n",arr3) 

1. 원본: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

2. 3개로 분활: 
 [array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]

3. 각 원소를 제곱: 
 [[[  4  16  36]]

 [[ 64 100 144]]

 [[196 256 324]]]

4. 행 기준으로 병합: 
 [[  2   4   6]
 [  8  10  12]
 [ 14  16  18]
 [  4  16  36]
 [ 64 100 144]
 [196 256 324]]


#### <실습예제 5>
- 삼각함수의 특수각(0,30,60,90)을 numpy.array로 생성
- 특수각에 해당하는 sin, cos, tan 값을 각각 구하시오.
- 파이썬 list에 담은 다음 해당 list에 들어있는 값들을 출력하시오.
- 단, 값이 무한대라면 "INF" 문자열을 출력한다)
- numpy에서 삼각함수는 radian 값을 사용하기 때문에 각을 radian으로 변경해야 한다.
- < degree * PI / 180 >

In [59]:
arr = np.arange(0, 91, 30)
print(arr)
items = []
items.append(np.sin( arr * np.pi / 180 ))
items.append(np.cos( arr * np.pi / 180 ))
items.append(np.tan( arr * np.pi / 180 ))

for item in items:
    for val in item:
        if val > 999999:
            print("INF")
            continue
        print(val)
    print()

[ 0 30 60 90]
0.0
0.49999999999999994
0.8660254037844386
1.0

1.0
0.8660254037844387
0.5000000000000001
6.123233995736766e-17

0.0
0.5773502691896257
1.7320508075688767
INF



#### <실습예제 6>
- numpy.array를 이용하여 다음과 같은 패턴을 출력하시오.
- 단, 출력 시 반복문을 사용하여 출력한다.

In [68]:
arr = np.zeros((7,7), dtype=int)
arr = np.full((7,7), 0)
print("1. 원본: \n",arr)

# 1로 치환
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
# 반복하여 출력
print("\n2. 결과:")
for row in range(7):
    for col in range(7):
        print(arr[row, col], end=" ")
    print()

1. 원본: 
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

2. 결과:
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
