1. 인공지능: 지능적 요소가 포함된 기술전체
2. 머신러닝: 데이터에서 모델을 스스로 찾아내는 방법 => sklearn, statesmodels
3. 딥러닝: NN(뉴럴네트웍:퍼셉트론)을 이용한 머신러닝 기법 => tensorflow, pytorch

- 0 Scalar s = 10
- 1 Vector v = [1,2]
- 2 Matrix m = [[1,2], [1,2]]
- 3 3-Tensor t3= [[[1,2], [1,2]][[1,2], [1,2]], [[1,2], [1,2]][[1,2], [1,2]]]
- n n-Tensor ....

In [2]:
import tensorflow as tf
import numpy as np

#### 01. constant 로 데이터 노드를 만든다.

In [3]:
s1 = 3.14
s2 = 100
s3 = 'korea'

In [10]:
c1 = tf.constant(s1)
c2 = tf.constant(s2)
c3 = tf.constant(s3)
c4 = tf.constant([10,20,30])
c5 = tf.constant( [[1,2,3], [4,5,6]] )
display(c1)
display(c2)
display(c3)
display(c4)
display(c5)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

<tf.Tensor: shape=(), dtype=int32, numpy=100>

<tf.Tensor: shape=(), dtype=string, numpy=b'korea'>

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30])>

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

#### 2. 요소별 연산(element wise)

In [14]:
a = tf.constant(3)          # scala
b = tf.constant([1,2,3])    # vector
c = tf.multiply(a,b) # c = a * b
display(c)
display(c.numpy()) # tensor > numpy nd array 객체로 변환

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

array([3, 6, 9])

[3, 6, 9]

In [16]:
d = tf.add(c,a) # d = c + a
display(d)
display(d.numpy())

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6,  9, 12])>

array([ 6,  9, 12])

##### 3. 요소별 브로딩 캐스트(Element wise) : 행렬 + 벡터

In [4]:
e = tf.constant([1,2,3])
f = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
g = e + f # tf.add(e, f)
display(g)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])>

In [5]:
e = tf.constant([1,2])
f = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
display( tf.add(e, f) ) # 오류가 발생한다. 행렬이 서로 맞지 않아서 에러가 발생

InvalidArgumentError: Incompatible shapes: [2] vs. [3,3] [Op:AddV2]

##### 4. 행렬 곱
- [행렬곱1](https://ko.wikipedia.org/wiki/%ED%96%89%EB%A0%AC_%EA%B3%B1%EC%85%88)
- [행렬곱2](https://namu.wiki/w/%ED%96%89%EB%A0%AC%EA%B3%B1)

In [8]:
# element wise x
h = tf.constant([[1,2], [3,4]])
i = tf.constant([[5,6], [7,8]])
j = tf.multiply(h, i) # j = h * i
display(j)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [9]:
# 행렬과 행렬 간의 행렬 곱
k = tf.matmul(h, i)
display(k)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [1]:
a = 2188800
b = 912000 * 3
b - a

547200