#### DataFrame 기본 속성

In [1]:
# 테스트 libary
import pandas as pd
import numpy as np

In [6]:
# 테스트 데이터
data = {'eng' :[10,30,50,70],
        'kor' :[20,40,60,80],
        'math':[90,50,20,70]}
df = pd.DataFrame(data, index=['a','b','c','d'])
display(df)

eng  kor  math
a   10   20    90
b   30   40    50
c   50   60    20
d   70   80    70

In [15]:
print( "%d 차원" % df.ndim)
print( "%d 행 X %d 열" % (df.shape[0], df.shape[1]))
print( "원소갯수: %d 개" % df.size)
print( "행의 갯수: %d" % len(df))

2 차원
4 행 X 3 열
원소갯수: 12 개
행의 갯수: 4


In [25]:
print(df.index)
print(df.columns,"\n")
print(df.dtypes, "\n")
print(df.values, "\n")
print(df.info(), "\n")
display(df.T) # 컬럼 > 인덱스로 변환

Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['eng', 'kor', 'math'], dtype='object') 

eng     int64
kor     int64
math    int64
dtype: object 

[[10 20 90]
 [30 40 50]
 [50 60 20]
 [70 80 70]] 

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   eng     4 non-null      int64
 1   kor     4 non-null      int64
 2   math    4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes
None 



a   b   c   d
eng   10  30  50  70
kor   20  40  60  80
math  90  50  20  70